<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Foot_Tracker</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppDesignerFolder>Resources</AppDesignerFolder>
    <ApplicationIcon>ProTracker_Pokeball.ico</ApplicationIcon>
  </PropertyGroup>

	<ItemGroup>
		<Content Include="SharedPokemonLibrary\Assets\Sprites\**\*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		
		<Content Include="SharedPokemonLibrary\Assets\Items\**\*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="SharedPokemonLibrary\Assets\Locations\**\*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<Content Include="SharedPokemonLibrary\Assets\Custom\**\*.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		
		<Content Include="SharedPokemonLibrary\Assets\Counterparts\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		
		<Content Include="SharedPokemonLibrary\Assets\Bosses\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <None Remove="DataFiles\Bosses\Ashwestbrook.json" />
    <None Remove="DataFiles\Bosses\Battlebot.json" />
    <None Remove="DataFiles\Bosses\Bruno.json" />
    <None Remove="DataFiles\Bosses\Bugsy.json" />
    <None Remove="DataFiles\Bosses\Chuck.json" />
    <None Remove="DataFiles\Bosses\Cie.json" />
    <None Remove="DataFiles\Bosses\Erika.json" />
    <None Remove="DataFiles\Bosses\GamersPewdieAndDiepy.json" />
    <None Remove="DataFiles\Bosses\George.json" />
    <None Remove="DataFiles\Bosses\GingeryJones.json" />
    <None Remove="DataFiles\Bosses\GuardianEntei.json" />
    <None Remove="DataFiles\Bosses\GuardianRaikou.json" />
    <None Remove="DataFiles\Bosses\GuardianSuicune.json" />
    <None Remove="DataFiles\Bosses\JessieAndJames.json" />
    <None Remove="DataFiles\Bosses\Klohver.json" />
    <None Remove="DataFiles\Bosses\Koichi.json" />
    <None Remove="DataFiles\Bosses\Lance.json" />
    <None Remove="DataFiles\Bosses\Letrix.json" />
    <None Remove="DataFiles\Bosses\Logan.json" />
    <None Remove="DataFiles\Bosses\Lorelei.json" />
    <None Remove="DataFiles\Bosses\LtSurge.json" />
    <None Remove="DataFiles\Bosses\Maribela.json" />
    <None Remove="DataFiles\Bosses\MedusaAndEldir.json" />
    <None Remove="DataFiles\Bosses\Misty.json" />
    <None Remove="DataFiles\Bosses\Morty.json" />
    <None Remove="DataFiles\Bosses\Naero.json" />
    <None Remove="DataFiles\Bosses\NarutoFanboy.json" />
    <None Remove="DataFiles\Bosses\Neroli.json" />
    <None Remove="DataFiles\Bosses\OfficerJenny.json" />
    <None Remove="DataFiles\Bosses\OfficerShamac.json" />
    <None Remove="DataFiles\Bosses\Prehax.json" />
    <None Remove="DataFiles\Bosses\ProfessorBirch.json" />
    <None Remove="DataFiles\Bosses\ProfessorElm.json" />
    <None Remove="DataFiles\Bosses\ProfessorOak.json" />
    <None Remove="DataFiles\Bosses\ProfessorRowan.json" />
    <None Remove="DataFiles\Bosses\Sage.json" />
    <None Remove="DataFiles\Bosses\Saphirr.json" />
    <None Remove="DataFiles\Bosses\SharyAndShaui.json" />
    <None Remove="DataFiles\Bosses\Spectify.json" />
    <None Remove="DataFiles\Bosses\Steven.json" />
    <None Remove="DataFiles\Bosses\Terminator.json" />
    <None Remove="DataFiles\Bosses\ThePumpkinKing.json" />
    <None Remove="DataFiles\Bosses\Thor.json" />
    <None Remove="DataFiles\Bosses\Tigerous.json" />
    <None Remove="DataFiles\Bosses\Toothless.json" />
    <None Remove="DataFiles\Bosses\Urahara.json" />
    <None Remove="DataFiles\Bosses\Xylos.json" />
    <None Remove="DataFiles\Maps\Kanto.json" />
    <None Remove="Data\PRO\capture-regions.json" />
    <None Remove="DataFiles\Bosses\Brock.json" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Blood.png" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Violet.png" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Midnight.png" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Pink.png" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Pride.png" />
    <None Remove="SharedPokemonLibrary\Assets\Custom\Slate.png" />
	<None Remove="SharedPokemonLibrary\Assets\Bosses\Ash_Westbrook.png" />
    <None Remove="DataFiles\Guides\Test\guide.css" />
    <None Remove="DataFiles\Guides\Test\index.html" />
    <None Remove="SharedPokemonLibrary\Data\Pokemon\pokemon-forms.json" />
    <None Remove="SharedPokemonLibrary\Data\Pokemon\pokemon-library.json" />
    <None Remove="SharedPokemonLibrary\Data\Pokemon\pokemon-species.json" />
    <None Remove="SharedPokemonLibrary\Data\Pokemon\sprite-map.json" />
    <None Remove="SharedPokemonLibrary\Data\Regions\Kanto\Route1.json" />
    <None Remove="SharedPokemonLibrary\Data\Regions\Kanto\Route2.json" />
    <None Remove="SharedPokemonLibrary\Data\Regions\Kanto\Route3.json" />
    <None Remove="SharedPokemonLibrary\Data\Regions\Kanto\Route4.json" />
    <None Remove="tessdata\eng.traineddata" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="DataFiles\Bosses\Ashwestbrook.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Bruno.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Bugsy.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Chuck.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Cie.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Erika.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\GamersPewdieAndDiepy.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\George.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\GingeryJones.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\GuardianEntei.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\GuardianRaikou.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\GuardianSuicune.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\JessieAndJames.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Klohver.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Koichi.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Lance.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Letrix.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Logan.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Lorelei.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\LtSurge.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Maribela.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\MedusaAndEldir.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Misty.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Morty.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Naero.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\NarutoFanboy.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Neroli.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\OfficerJenny.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\OfficerShamac.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Prehax.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\ProfessorBirch.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\ProfessorElm.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\ProfessorOak.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\ProfessorRowan.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Sage.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Saphirr.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\SharyAndShaui.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Spectify.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Steven.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Terminator.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\ThePumpkinKing.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Thor.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Tigerous.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Toothless.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Urahara.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Xylos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\counterparts.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Maps\Kanto.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\PRO\capture-regions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Bosses\Brock.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ProTracker_Pokeball.ico" />
    <Content Include="SharedPokemonLibrary\Assets\Custom\Blood.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Assets\Custom\Violet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Assets\Custom\Midnight.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Assets\Custom\Pink.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Assets\Custom\Pride.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Assets\Custom\Slate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="DataFiles\Bosses\BattleBot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Guides\Test\guide.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Guides\Test\index.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Metadata\sprite-map.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Pokemon\pokemon-forms.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Pokemon\pokemon-library.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Pokemon\pokemon-species.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Regions\Kanto\Route1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Regions\Kanto\Route2.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Regions\Kanto\Route3.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SharedPokemonLibrary\Data\Regions\Kanto\Route4.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<Content Include="Assets\Guides\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="DataFiles\Forms\**" />
	  <EmbeddedResource Remove="DataFiles\Forms\**" />
	  <None Remove="DataFiles\Forms\**" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="DataFiles\LegendaryPokemon\" />
    <Folder Include="Forms\Cooldowns\Excavations\" />
    <Folder Include="Forms\Cooldowns\Digs\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Easter\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\May4th\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Halloween\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Christmas\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\PikachuWQ\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Summer\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Valentines\" />
    <Folder Include="SharedPokemonLibrary\Assets\Counterparts\Shadow\" />
    <Folder Include="SharedPokemonLibrary\Assets\Icons\" />
    <Folder Include="SharedPokemonLibrary\Assets\Fonts\" />
	<Folder Include="SharedPokemonLibrary\Assets\Bosses\" />
    <Folder Include="SharedPokemonLibrary\Data\Regions\Johto\" />
    <Folder Include="SharedPokemonLibrary\Data\Regions\Hoenn\" />
    <Folder Include="SharedPokemonLibrary\Data\Regions\Astrella\" />
    <Folder Include="SharedPokemonLibrary\Data\Regions\Sevii\" />
    <Folder Include="SharedPokemonLibrary\Data\Regions\Sinnoh\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>

</Project>